### ISSUE TITLE
Is the Auth0 Fine Grained Authorization open-source?

### ISSUE THREAD

**Issue by erickhgm** [auth0-lab/fga-go-sdk#3]
Hello, how are you guys?

I have a question based on this text part:

> [Auth0 Fine Grained Authorization (FGA)](https://fga.dev/) is an open source Fine-Grained Authorization solution inspired by [Google's Zanzibar paper](https://research.google/pubs/pub48190/). It was created by the FGA team at [Auth0](https://auth0.com/) based on [Auth0 Fine-Grained Authorization (FGA)](https://fga.dev/), available under [a permissive license (Apache-2)](https://github.com/auth0-lab/rfcs/blob/main/LICENSE) and welcomes community contributions.

Where is the source code of `Auth0 Fine Grained Authorization`?
I'm evaluating open-source projects like `Zanzibar` to use here in my company.

**Comment by adriantam** [comment]
> Hello, how are you guys?
> 
> I have a question based on this text part:
> 
> > [Auth0 Fine Grained Authorization (FGA)](https://fga.dev/) is an open source Fine-Grained Authorization solution inspired by [Google's Zanzibar paper](https://research.google/pubs/pub48190/). It was created by the FGA team at [Auth0](https://auth0.com/) based on [Auth0 Fine-Grained Authorization (FGA)](https://fga.dev/), available under [a permissive license (Apache-2)](https://github.com/auth0-lab/rfcs/blob/main/LICENSE) and welcomes community contributions.
> 
> Where is the source code of `Auth0 Fine Grained Authorization`? I'm evaluating open-source projects like `Zanzibar` to use here in my company.

Hello @erickhgm ,
Please refer to OpenFGA (https://openfga.dev/) for the open source projects like Zanzibar.

**Comment by erickhgm** [comment]
Thank you @adriantam, yesterday I searched a little more and I found it.
